
languageCode = 'en-us'
defaultContentLanguage = "en"
title = 'RevMetrix'

theme = "hugo-theme-relearn"
[markup.goldmark.renderer]
unsafe= true

[outputs]
home = [ "HTML", "RSS", "SEARCH", "SEARCHPAGE"]

[params]
disableLanguageSwitchingButton = false
disableLandingPageButton = true
collapsibleMenu = true
editURL = "https://github.com/YCP-Rev-Metrix/Wiki/edit/main/content/"
# Change default color scheme with a variant one.
themeVariant = [ "neon", "auto", "zen-light", "zen-dark", "blue", "green", "learn", "red", "relearn", "relearn-bright", "relearn-light", "relearn-dark" ]

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-paperclip'></i> CS400 RevMetrix Home Page"
identifier = "ds"
url = "https://ycpcs.github.io/cs400-fall2023/projects/RevMetrix-Project/index.html"
weight = 1

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-paperclip'></i> CS402 RevMetrix Home Page"
url = "https://ycpcs.github.io/cs402-spring2024/projects/RevMetrix-Project/index.html"
weight = 1

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub Organization"
url = "https://github.com/YCP-Rev-Metrix"
weight = 2

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-google-drive'></i> Google Drive"
url = "https://drive.google.com/drive/folders/1Z_TtR7IVxIza5YR7sO4sxDVqkagdBix5?usp=drive_link"
weight = 3

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
url = "more/credits/"
weight = 4

[languages]
[languages.en]
title = "Hugo Relearn Theme"
weight = 5
languageName = "English"

[languages.pir]
title = "Cap'n Hugo Relearrrn Theme"
weight = 6
languageName = "Arrr! Pirrrates"

[markup.tableOfContents]
startLevel = 0
endLevel = 0
